title = "BEAM Mignon"
baseURL = "https://beam-mignon.netlify.com/"
languageCode = "pt-br"
theme = "ananke"
DefaultContentLanguage = "pt-br"
copyright = "https://creativecommons.org/licenses/by/4.0/"
enableRobotsTXT = true
Paginate = 15
SectionPagesMenu = "main"
googleAnalytics = "UA-145112810-1"
disqusShortname = "beammignon"

[languages]
  [languages.pt-br]
    languageName = "Brazilian Portuguese"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/joaohf/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/joão-henrique-freitas"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/stockholm.jpg"
  recent_posts_number = 6

[author]
  name = "João Henrique Ferreira de Freitas"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[related]
threshold = 80.0
includeNewer = true
toLower = false

  [[related.indices]]
  name = "series"
  weight = 100.0

  [[related.indices]]
  name = "tags"
  weight = 110.0

  [[related.indices]]
  name = "date"
  weight = 10.0
